# -*- coding: utf-8 -*-
"""model.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1AeRzMI7MjUzTeFd7wXEuqKIgmqjaxAMc
"""

from google.colab import drive
drive.mount('/content/drive')

!apt-get install -y unrar

!unrar x "/content/drive/MyDrive/Colab Notebooks/fruitsDataset.rar" "/content/data/"

import os
os.listdir("/content/data/")

train_path = "/content/data/fruitsDataset/Training"
test_path = "/content/data/fruitsDataset/Test"

import tensorflow as tf
import matplotlib.pyplot as plt
import numpy as np
import time
from sklearn.metrics import confusion_matrix, ConfusionMatrixDisplay

train_path = "/content/data/fruitsDataset/Training"
test_path = "/content/data/fruitsDataset/Test"

train_data = tf.keras.utils.image_dataset_from_directory(
    train_path,
    image_size=(80, 80),
    batch_size=16
)

test_data = tf.keras.utils.image_dataset_from_directory(
    test_path,
    image_size=(80, 80),
    batch_size=16
)

train_data = train_data.map(lambda x,y: (x/255.0, y))
test_data = test_data.map(lambda x,y: (x/255.0, y))

val_size = int(0.2 * len(train_data))
val_data = train_data.take(val_size)
train_data = train_data.skip(val_size)

# -------- MLP --------
mlp = tf.keras.Sequential([
    tf.keras.layers.Input(shape=(80,80,3)),
    tf.keras.layers.Flatten(),
    tf.keras.layers.Dense(128, activation='relu'),
    tf.keras.layers.Dense(3, activation='softmax')
])

mlp.compile(optimizer='adam',
            loss='sparse_categorical_crossentropy',
            metrics=['accuracy'])

start = time.time()
hist_mlp = mlp.fit(train_data, validation_data=val_data, epochs=2, verbose=0)
mlp_time = time.time() - start

mlp_loss, mlp_acc = mlp.evaluate(test_data, verbose=0)

# -------- CNN --------
cnn = tf.keras.Sequential([
    tf.keras.layers.Conv2D(16,(3,3),activation='relu',input_shape=(80,80,3)),
    tf.keras.layers.MaxPooling2D(2,2),
    tf.keras.layers.Conv2D(32,(3,3),activation='relu'),
    tf.keras.layers.MaxPooling2D(2,2),
    tf.keras.layers.Flatten(),
    tf.keras.layers.Dense(64,activation='relu'),
    tf.keras.layers.Dense(3,activation='softmax')
])

cnn.compile(optimizer='adam',
            loss='sparse_categorical_crossentropy',
            metrics=['accuracy'])

start = time.time()
hist_cnn = cnn.fit(train_data, validation_data=val_data, epochs=2, verbose=0)
cnn_time = time.time() - start

cnn_loss, cnn_acc = cnn.evaluate(test_data, verbose=0)

# -------- PLOTS --------
def plot_graph(h, name):
    plt.plot(h.history['accuracy'])
    plt.plot(h.history['val_accuracy'])
    plt.title(name + " Accuracy")
    plt.legend(['train','val'])
    plt.show()

    plt.plot(h.history['loss'])
    plt.plot(h.history['val_loss'])
    plt.title(name + " Loss")
    plt.legend(['train','val'])
    plt.show()

plot_graph(hist_mlp, "MLP")
plot_graph(hist_cnn, "CNN")

# -------- CONFUSION MATRIX --------
y_true = []
y_pred = []

for x, y in test_data:
    p = cnn.predict(x, verbose=0)
    y_true.extend(y.numpy())
    y_pred.extend(np.argmax(p, axis=1))

cm = confusion_matrix(y_true, y_pred)
ConfusionMatrixDisplay(cm).plot()
plt.show()

# -------- RESULTS --------
print("MLP Acc:", mlp_acc)
print("MLP Loss:", mlp_loss)
print("MLP Time:", mlp_time)
print("MLP Params:", mlp.count_params())

print("CNN Acc:", cnn_acc)
print("CNN Loss:", cnn_loss)
print("CNN Time:", cnn_time)
print("CNN Params:", cnn.count_params())

